// GENERATED by scripts/build-content.js — do not edit by hand.
// Source of truth is content/*.md
//
// SERVER-SIDE ONLY. This module is imported by functions/ (Pages Functions) and is
// never referenced from src/, so Vite does not bundle it into the client. If you
// ever import it from React, the full prompts ship to the browser and the paywall
// stops meaning anything.
export default [
  {
    "id": "70da21de7160",
    "title": "Brutalist Architecture, Overcast",
    "tags": [
      "architecture",
      "minimal",
      "concrete"
    ],
    "image": "/images/auto-70da21de7160-f84cdebb.jpg",
    "teaserChars": 66,
    "words": 62,
    "prompt": "Frontal architectural photograph of a brutalist concrete community centre under a flat overcast sky, shot on a tilt-shift lens for perfectly corrected verticals, board-formed concrete texture with visible tie holes and weather staining, no people, no cars, cold neutral grey palette with a single muted green door as the only colour accent, diffuse shadowless light, medium format detail, symmetrical composition, printed-in-a-monograph aesthetic"
  },
  {
    "id": "b735f90e0ed8",
    "title": "Cinematic Night Rain, Anamorphic",
    "tags": [
      "cinematic",
      "night",
      "neon"
    ],
    "image": "/images/auto-b735f90e0ed8-60f84428.jpg",
    "teaserChars": 72,
    "words": 75,
    "prompt": "Cinematic wide shot of a lone figure with an umbrella crossing an empty intersection at 2am in heavy rain, anamorphic 2.39:1 with horizontal blue lens flares, shot on Cooke lenses at T2.8, wet asphalt acting as a mirror for the sodium streetlights, practical light sources only, teal shadows against warm amber highlights, visible rain streaks lit from behind, shallow depth of field with oval bokeh, film grain, colour graded like a Roger Deakins night exterior"
  },
  {
    "id": "7ae24955a82c",
    "title": "Editorial Food, Dark Kitchen",
    "tags": [
      "food",
      "editorial",
      "moody"
    ],
    "image": "/images/auto-7ae24955a82c-cd2fb4c9.jpg",
    "teaserChars": 70,
    "words": 72,
    "prompt": "Overhead editorial food photograph of a rustic lemon and thyme tart on a chipped enamel plate, dark moody kitchen setting, single hard window light from the upper right with deep falloff to near-black on the left, scattered crumbs and a linen napkin with natural creases, steam barely visible, shot at f/5.6 on a 100mm macro for edge-to-edge crispness on the tart, desaturated palette except the saturated yellow of the lemon, restaurant-cookbook aesthetic"
  },
  {
    "id": "de6801085a74",
    "title": "Isometric Cutaway Workshop",
    "tags": [
      "isometric",
      "3d",
      "illustration"
    ],
    "image": "/images/auto-de6801085a74-6c02427d.jpg",
    "teaserChars": 68,
    "words": 73,
    "prompt": "Isometric cutaway illustration of a cluttered watchmaker workshop rendered as a miniature diorama, 45-degree axonometric projection, warm tungsten desk lamp as the single light source casting long soft shadows, matte clay-render materials with subtle subsurface scattering on the wooden surfaces, tiny brass tools and loupe scattered on the bench, dust motes catching the light, muted ochre and deep teal palette, clean white background outside the cutaway, extremely fine detail on the small objects"
  },
  {
    "id": "3ce04f2682aa",
    "title": "Kodak Portra Street Portrait",
    "tags": [
      "portrait",
      "film",
      "analog"
    ],
    "image": "/images/auto-3ce04f2682aa-2a0f18ee.jpg",
    "teaserChars": 74,
    "words": 70,
    "prompt": "Candid half-body portrait of a woman in her early thirties on a narrow city street, shot on Kodak Portra 400 with an 85mm f/1.4 lens wide open, late afternoon sun raking from camera left, soft falloff into a creamy out-of-focus background of shopfronts, natural skin texture with visible pores and fine grain, muted terracotta and sage colour palette, slight halation on highlights, no retouching, photographed at eye level, 4:5 crop"
  },
  {
    "id": "b1828827eb18",
    "title": "Risograph Poster Texture",
    "tags": [
      "graphic",
      "print",
      "retro"
    ],
    "image": "/images/auto-b1828827eb18-42ef5231.jpg",
    "teaserChars": 62,
    "words": 59,
    "prompt": "Two-colour risograph print poster design of a mountain range, fluorescent pink and deep navy inks only, deliberate 2mm misregistration between the layers, visible paper tooth and uneven ink coverage with roller streaks, heavy dot-screen texture in the mid-tones, off-white recycled paper stock, flat vector shapes with no gradients, generous negative space in the upper third, 1970s Japanese travel-poster composition"
  },
  {
    "id": "ff0728c45dfc",
    "title": "Swiss Alpine Travel Poster, 1930s",
    "tags": [
      "poster",
      "vintage",
      "travel"
    ],
    "image": "/images/auto-ff0728c45dfc-7fd22230.jpg",
    "teaserChars": 64,
    "words": 66,
    "prompt": "Vintage 1930s Swiss tourism travel poster of a funicular railway climbing toward a snow-capped alpine peak, flat gouache-style shapes with hand-airbrushed gradients, limited five-colour palette of cream, cobalt, alpine rose, deep pine and warm grey, geometric Art Deco stylisation of the mountain ridges, bold condensed sans-serif lettering reserved along the bottom third, subtle offset-litho paper grain, high contrast between the sunlit snowfield and the shadowed valley"
  }
];
