import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CONTENT = path.join(ROOT, 'content');
const IMAGES = path.join(ROOT, 'public', 'images');
const OUT = path.join(ROOT, 'src', 'movies.js');

fs.mkdirSync(IMAGES, { recursive: true });
fs.mkdirSync(CONTENT, { recursive: true });

function parse(file) {
  const raw = fs.readFileSync(path.join(CONTENT, file), 'utf8');
  const meta = {};
  let body = raw;

  const fm = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (fm) {
    for (const line of fm[1].split(/\r?\n/)) {
      const i = line.indexOf(':');
      if (i > 0) meta[line.slice(0, i).trim().toLowerCase()] = line.slice(i + 1).trim();
    }
    body = fm[2];
  }

  const synopsis = body.split(/\r?\n/).map((l) => l.trim()).filter(Boolean).join(' ').trim();

  if (!meta.title) return null;

  const slug = file.replace(/\.[^.]+$/, '');

  return {
    slug,
    file,
    title: meta.title,
    year: meta.year ? Number(meta.year) : null,
    runtime: meta.runtime || null,
    genre: meta.genre || null,
    cast: (meta.cast || '').split(',').map((c) => c.trim()).filter(Boolean),
    videoEmbedUrl: meta.videoembedurl || meta.video || null,
    trailerUrl: meta.trailerurl || meta.trailer || null,
    manualImage: meta.image || null,
    manualBackdrop: meta.backdrop || null,
    synopsis,
  };
}

function resolveImage(slug, manual, extraExts = []) {
  if (manual && fs.existsSync(path.join(IMAGES, manual))) return `/images/${manual}`;

  for (const ext of ['jpg', 'jpeg', 'png', 'webp', ...extraExts])
    if (fs.existsSync(path.join(IMAGES, `${slug}.${ext}`))) return `/images/${slug}.${ext}`;

  return null;
}

const files = fs.readdirSync(CONTENT)
  .filter((f) => /\.md$/i.test(f) && !f.startsWith('_') && !f.startsWith('.'))
  .sort();

console.log(`[content] ${files.length} file(s) in content/`);

const out = [];
let skipped = 0;

for (const file of files) {
  const item = parse(file);
  if (!item) { console.warn(`  ! ${file} — missing title, skipped`); skipped++; continue; }

  const poster = resolveImage(item.slug, item.manualImage);
  if (!poster) {
    console.error(`  ✗ ${file} — no poster image found (looked for /public/images/${item.slug}.{jpg,png,webp} or an image: field), EXCLUDED`);
    skipped++;
    continue;
  }

  const backdrop = resolveImage(`${item.slug}-backdrop`, item.manualBackdrop) || poster;

  out.push({
    id: item.slug,
    title: item.title,
    year: item.year,
    runtime: item.runtime,
    genre: item.genre,
    poster,
    backdrop,
    synopsis: item.synopsis || null,
    cast: item.cast,
    videoEmbedUrl: item.videoEmbedUrl,
    trailerUrl: item.trailerUrl,
  });
  console.log(`  · ${item.title} (${item.slug})`);
}

const banner = `// GENERATED by scripts/build-content.js — do not edit by hand.
// Source of truth is content/*.md + public/images/
`;

fs.writeFileSync(OUT, `${banner}export const MOVIES = ${JSON.stringify(out, null, 2)};\n`);

console.log(`[content] wrote src/movies.js — ${out.length} movie(s)`);
if (skipped) console.warn(`[content] ${skipped} file(s) excluded (see warnings above)`);
